# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qLdG6jTIcNl7rNBZtJ44F4H3xSl/6H/YmAawG+35RXvGrkHU7TrY6NIhh/rgA3o5C+QAydCcnCKAV+VOM/78atVRmcoBsQsUoaaFUIQdGDL9ej9dcyjVME4SZW15eaY/xU4rsjoDPI1C/ZIpcHHhlmz+Xx3b818MV+SFDBxr6mMae9fAAHkDAkYSHBxl4l93mv+fQEvEP1IjQFygDTmjtQ/V1rdot31YVYaWj67q7jgN8+1TEMtzfKRgZPCNy0zj+vg3AVykUbD4PWcKQ0PwvNaUZBbuhkS9IZEmLVUox3/WVz/WNRwq1mBUkkWtbORbW2chlNDpwN2b3/Qp6hmdrGmilC4+YCz7TIaNhoO2n4j98EIUaoFiB5Xs86ZiWNrSZRpcEYs0V4io7ZXFxVJPY3IaCnfPnsQhK0ZlpEwKP7TgoRXllMKZ+HYSaH10xRK5X84xCivMuGOUX0WK0Hh6MojJP6UTeYfUEH0kLLPNDXTSR03dEBaq7nwPY27S7CZ1p25ElZuHhaHRseidtUz7nbqNEeIgiNpkZXAgBFbxQFy+lZT4CWaRa3SYhqLeinSgRrAEzpjVoaFOVH/cInWAJq0j0qVVzhYtDHix12ZMhjsxVoPOFXl9FGh6lSueYQtFvvQ7GCIn7uEA0IAdkM1zS+vTqQNgoFarTkgDeqwUgGI="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
