travis:
  secure:
    BINSTAR_TOKEN: qLdG6jTIcNl7rNBZtJ44F4H3xSl/6H/YmAawG+35RXvGrkHU7TrY6NIhh/rgA3o5C+QAydCcnCKAV+VOM/78atVRmcoBsQsUoaaFUIQdGDL9ej9dcyjVME4SZW15eaY/xU4rsjoDPI1C/ZIpcHHhlmz+Xx3b818MV+SFDBxr6mMae9fAAHkDAkYSHBxl4l93mv+fQEvEP1IjQFygDTmjtQ/V1rdot31YVYaWj67q7jgN8+1TEMtzfKRgZPCNy0zj+vg3AVykUbD4PWcKQ0PwvNaUZBbuhkS9IZEmLVUox3/WVz/WNRwq1mBUkkWtbORbW2chlNDpwN2b3/Qp6hmdrGmilC4+YCz7TIaNhoO2n4j98EIUaoFiB5Xs86ZiWNrSZRpcEYs0V4io7ZXFxVJPY3IaCnfPnsQhK0ZlpEwKP7TgoRXllMKZ+HYSaH10xRK5X84xCivMuGOUX0WK0Hh6MojJP6UTeYfUEH0kLLPNDXTSR03dEBaq7nwPY27S7CZ1p25ElZuHhaHRseidtUz7nbqNEeIgiNpkZXAgBFbxQFy+lZT4CWaRa3SYhqLeinSgRrAEzpjVoaFOVH/cInWAJq0j0qVVzhYtDHix12ZMhjsxVoPOFXl9FGh6lSueYQtFvvQ7GCIn7uEA0IAdkM1zS+vTqQNgoFarTkgDeqwUgGI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
