travis:
  secure:
    BINSTAR_TOKEN: m3h2qh+4llZarSMnP/ZDbPKLbHayICzZTwI3M2BUtB9/l/67tb1q0m1eQqyM+yWqkcvrc/BSFvW8SdBwSrhSXZBaWG8y+e1DDwuO+3wDV7/nAt6166YJqVVXBuVGPDOLjW4cXLNhLIp2HNuIrVjPZHPxYwp1Gwk71hcamHuZlDEqQKByV88tBVzYpLJ0C6bzoRsownHEgW+TQno5kL3vb0XcXDxGmUVTApL99Rn49Z+BqGKPJOLoo79Itn0hg72Jd1C88u5nwWsc+tXQBRDXJy6FaJVPgqYdM65JcV3WBcDo0bqsmSFLmc5UQ88t3r1Fxhp03GdduvJRC0oqpA9Y+hzBMshVpJ0ClAAsdd2XKY0N9ftu1LNa4vhCZ4jyAA/g3EsnqQR47n/juLzXRCcN9eXDozTWvojVBp2oM2qw6muKv3agBPxcEEjIF/lm3BbaVox4JrTW6jKlyWYKWnCEtlJWqoO/yWQCSSArj0Wo/lhDgA5ijFK7+DwJEPBgBqMpNHIlfoMMUPFLSvLZwZX8Dly8rly0iCcz3F753hV6DGsUcAZFbe5BHbSZvV8mHLl3W1vV0t4do99I4D7teA06Kafgwm19r67uqc8BWrP75MICASb8pvv1rq6wx1H9G6Vx20mTnUJApTsDeICCteXwqpnQ69e9YzyENQfS/5tQPXA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
