travis:
  secure:
    BINSTAR_TOKEN: wC80G9sL8/VNizVX0IUODVyEVxSOUHobyO4+lkEy9BAr7FdfkaHmFgv3Y1WQk3JT5SbhDvg7PLhKL5uZthPTdlpQDuaMqMY+FfDLocklqxDwjwluaY+gwU8Bux75nIAoPzDTUCOMRj8u0ctEJPEtfAIooUJtcDUX14bF4W3CQ5c+OAIXKgwEVsTvmmbL67u4fZ8Ch16URmc1L0cU0lFOPYUpTptRvwcaAOxB0JMck0492r8ixxi0Ch/2qFrqkqzps29p26Io99cOv1TjeBLZMi5up9nbvVGpfoF6UWDN7RWX0BHpeVsaKlARrE49Z5u7ud4ZRza7/YscNw3DGzTqC1R9EpH/RL3b/xSPhUNLBWETJ0NoVhREZUQWoZPQjp40YZzDrX6RVyQ+qwHRBFgonzkaTl0qH1QoVkoAeVVTjN+0ohKVBIKrpP+NReZ9N+EP7GmhfCQczzllT3BIhA/WPHTh75lJN/IMQCyn65NQAUZ9ZUZ1zfrXZVqb2QibScBI4+HHvM7lI4xgXdsEO1fzjxgbLvIjcyGN5vND+Tq0ZzQYjQgiyarO6nPOakasJJzpe79hRM0Wo1VO12JVwskCX1ciJzzr3r3iZMkm8MqWs4JTeK5DnYyZ1z17KpxZoG91R8evy+DLoI2f7XpKCKZYHhNrhDaejbKvvPHm5erTJfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
