travis:
  secure:
    BINSTAR_TOKEN: 4frx++nk2MX6tZTzMdw+ge7Hpf7pt9rKTxrBir1qUAazM2PqTaFS9Rn61j4mRBLDZPWio7YQGAyQsqXNeXTF6G7p1vmN9PnXGBQ78t+Vn7fE47/qsKVrHn8MyOq6uS73jje0UU0/18bIixT1P1ZMIwhVX++bj/dfMRs9u6e1JRskTwzBVPqdSeVrT2pl80+JmzN1M74sUs3aaGo8X6Jq8Hq67MpD3GvnNibzoTT0z1n2pHMxRk+3JTMZUZJ0WM2geSAlb7xIFyVpRjluHh0lqnQVBrLZwAGuK4CxeSX3USH96dmrkIJVR0rs0SXq2/ajVqIKqv3F8di1+aRtwYhYVBMUjnGmxuz2mpVG7yMYEnR0QkMIK9OVg+ARMZKBSwDFAXp1927bIKmzud7MwpEGDmYQVp1xThsnLzjMnyx4vsqXq9AdEJBqMtxGorQU327bFJJ23F1qnLu4bum/0EFqxX1t9PztnCr4XnOdPbaxz7cSz3Fob5LoRLjU7Q4ahcpU6JkjuX8khwr7/Cpy1DD20RySnmVMVu76Oh4mzo2v9/ru0waLKTcX/EQ+9PfmSUM9RCYr5LEKvsVwTDe5LlhSiCEUToqMe0I4GWKBsf+pLBmnD8b+tEcI4A2yuL8lHKsaCxjpbpROOyFZrnUqg26jqr+bYhCj8lVb7LYjGbNdGEw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
