travis:
  secure:
    BINSTAR_TOKEN: ieJvXiaSlVtpzqDbIQmjC3UXaLG65D4wlsgG8oqHKHBevUecLUCyOdW03tj8DQX/Ig4Ow4AjNGa1HIazt63XtFm/jWF+eKbM7IR+0a5LgvKfspN45qZ/KFG24mFEqCd17GI8bBHeq1bZXGlaEKLgUwVv3AcsyOzYeuIU8wzupZ/hUrpIA6P8XlKtUMgKi55bpK9ZWQ/Z2GjT1TinruVfiCyQ4gjGSxsJwuqTp78KStQPPCnlws0GXB7aDzqWoO+R0AJDMjRk7XWSaBv8edGwgMA4hsoC2th3jynvAdSr3kfyv6MnEenBEd3JiQtHFs7PeBELV+mC9QphJguBouKzIPg/Cjnd7B5WuWIHJnv7TYISuE7RkgR6TIJny4zsWDpZdnUm7YPD/ZBKAZcvLF2UP9lIaGll8ubxQdNklRODbG6N6rAuVu7W0yRz4ph+MaqnEhCOrGkii2oHWW9h87+P2MKuraAy3YiTxAm6rrWcQPSVHexT3h2Zl19GYLiinWYIVzpzDtF3TCIjBgjEzT1mWJICvpw3x+lV9DP/Ka4kN3Twx+jivz9HWfgZoRq0763oKDmLwWZVR2cKoMfCksa5KYhgGb899kmPJWv7fYfY6n1YAFfJI83F/7n3Bz3U8cHgfcMh1STGo0vYmHgs4kyuFy4yLD14+pGvMqFYOIOPt8o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
