travis:
  secure:
    BINSTAR_TOKEN: NUMuL63pRxmQzBe6Nm4aJpfOT6+NW8xIwT3yfY6W+4m1wGu/dQUwed8+NjVZj6LSz76f5XU/ktFRCXyjuRV8dyyGrxwawCdv+kOqo3yCMjZIEYvNUvUb0vy3MgY8N9LXaG2X7zWG+DcoKlUcbwSAuY+OcHaipg5yKG2+fZbj/aFsZUX1brxwO5/44WJ4N5Vu7vz4KS04LKEGcFYdWKToqCbQYiBAnVBhi9JWPcPVY96Pnc1xw6iaw4qF2dyL83uB9CEMDEZgM9/6JTXHBc5t90DYoGDYQffGZdHCxOJSWPKXKP4UmzEn/6m8PHROXRJFpZkr0SYQmGGLoFT8JRSOHqHlEo6vef9cZw4qGf5t+FkVFV4cPdtzpX4c7VIekF0pcPxICugEyixyf4Z9hB/tfbTgWiCMkxQf2YF1URMbGUeShDr0YV7ePdDscqjmRGlP09bFqFfCaqYiaswvLjnc9/ZTEhP5otVdBKRukY33DTdXI9RDMhxTCxHVtlOsNAoD84MCYeom+o7ZD13cATzUnmzRJVLtL5HPn0y49S4sssg027YJTHWk1M1mxamrMXKJ9CK+J5Epi4TIL10hiqZDFOZ3NNpPo2qlTItQN4sl712oX7J/c+jEZIv5JnYVf7Ze63/gRwfEgWXOrHOZRuAhzh/3BiNr9IQwCaP+7PiUBYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
